# Generated by Django 2.2.12 on 2020-05-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='z_dim',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='x_dim',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='y_dim',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
